name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
              python -m pip install --upgrade pip
              # Force TensorFlow 2.15 to maintain compatibility with your saved model
              pip install "tensorflow==2.15.0" 
              pip install -r requirements.txt
              pip install pytest
    - name: Run Unit Tests
      # This targets your specific test directory and stops the workflow if they fail
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest src/tests/

    - name: Basic check
      run: |
        echo "Tests passed. Proceeding to build..."

    - name: Build Docker image
      run: |
        docker build -t fer-project .

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: |
        docker tag fer-project ${{ secrets.DOCKER_USERNAME }}/fer-project:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/fer-project:latest
